module.exports = {
  purge: [
    './src/**/*.html',
    './src/**/*.js',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    fontFamily: {
      'tahu': ['Tahu'],
      'gotham': ['Gotham Book'],
    },
    extend: {
      fontSize: {
        '2xs': '0.5rem',
        '3xs': '0.4rem',
        '4xs': '0.3rem'
      },
      height: {
        'hero-xs' : '500px',
        'hero-sm' : '340px',
        'hero-md' : '410px',
        'hero-lg' : '550px',
        'hero-xl' : '670px',
        'hero-2xl' : '820px',
        'video-thumb-sm' : '50px',
        'video-thumb-md' : '240px',
        'video-thumb-lg' : '350px',
        'video-thumb-xl' : '460px',
        'video-thumb-2xl' : '543px',
        'event-lg' : '1000px',
        'event-xl' : '527px',
        'event-2xl' : '627px',
        'logo-ig-sm' : '16px',
        'logo-ig-md' : '16px',
        'logo-ig-lg' : '26px',
        'logo-ig-xl' : '36px',
        'logo-ig-2xl' : '46px',
        'speaker-sm' : '24px',
        'speaker-md' : '44px',
        'speaker-lg' : '64px',
        'speaker-xl' : '84px',
        'speaker-2xl' : '103px',
        'presiden-banner' : '310px',
        'arrow-right' : '10px',
        'card-news' : '428px',
        'thumb' : '175px',
        'logo-bank-btn' : '73px',
        'logo-waskita' : '70px',
        'top-arrow': '27px',
        'logo-bisnis-bottom': '35px'
      },
      backgroundImage: {
        'shape-red': "url('../images/heros/shape_red.png')",
        'vector-pattern': "url('../images/heros/vector.png')",
        'logo-bisnis-top': "url('../images/heros/logo_bisnis_top.png')",
        'logo-indonesia-maju-top': "url('../images/heros/logo_indonesia_maju_top.png')",
        'video-thumb': "url('../images/heros/video_thumb.png')",
        'icon-player': "url('../images/heros/icon_player.png')",
        'event-1-ig': "url('../images/widgets/instagram_1/bg-img.png')",
        'event-2-ig': "url('../images/widgets/instagram_2/bg-img.png')",
        'logo-ig-1': "url('../images/widgets/instagram_1/logo-ig.png')",
        'logo-live-1': "url('../images/widgets/instagram_1/logo-live.png')",
        'logo-ig-tiny-1': "url('../images/widgets/instagram_1/logo-ig-tiny.png')",
        'speaker-1-1': "url('../images/widgets/instagram_1/speaker1.png')",
        'speaker-2-1': "url('../images/widgets/instagram_1/speaker2.png')",
        'bg-name-speaker1': "url('../images/widgets/instagram_1/bg-name-speaker.png')",
        'logo-ig-2': "url('../images/widgets/instagram_2/logo-ig.png')",
        'logo-live-2': "url('../images/widgets/instagram_2/logo-live.png')",
        'logo-ig-tiny-2': "url('../images/widgets/instagram_2/logo-ig-tiny.png')",
        'speaker-1-2': "url('../images/widgets/instagram_2/speaker1.png')",
        'speaker-2-2': "url('../images/widgets/instagram_2/speaker2.png')",
        'presiden-banner': "url('../images/widgets/banner/presiden.png')",
        'shape': "url('../images/widgets/banner/shape.png')",
        'arrow-right': "url('../images/widgets/card_news/arrow-right.png')",
        'card-news': "url('../images/widgets/card_news/card-news.png')",
        'thumb-1': "url('../images/widgets/card_news/thumb-1.png')",
        'thumb-2': "url('../images/widgets/card_news/thumb-2.png')",
        'thumb-3': "url('../images/widgets/card_news/thumb-3.png')",
        'hr': "url('../images/footers/hr.png')",
        'logo-bisnis-bottom': "url('../images/footers/logo-bisnis-bottom.png')",
        'logo-bank-btn': "url('../images/footers/logo-bank-btn.png')",
        'logo-waskita': "url('../images/footers/logo-waskita.png')",
        'top-arrow': "url('../images/footers/top-arrow.png')",
      }
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
