export const styled = {
    hero: {
        xxl: '2xl:bg-red-600 2xl:h-hero-2xl 2xl:max-w-full',
        xl: 'xl:bg-green-600 xl:h-hero-xl xl:max-w-full',
        lg: 'lg:bg-gray-600 lg:h-hero-lg lg:max-w-full',
        md: 'md:bg-yellow-600 md:h-hero-md md:max-w-full',
        sm: 'sm:bg-blue-600 sm:h-hero-sm max-w-full',
        mobile: 'bg-red-600 h-hero-xs max-w-full',
    },
    vector: {
        xxl: '2xl:bg-vector-pattern 2xl:bg-no-repeat 2xl:w-full 2xl:text-center 2xl:bg-contain 2xl:bg-center 2xl:h-hero-2xl',
        xl: 'xl:bg-vector-pattern xl:bg-no-repeat xl:w-full xl:text-center xl:bg-contain xl:bg-center xl:h-hero-xl',
        lg: 'lg:bg-vector-pattern lg:bg-no-repeat lg:w-full lg:text-center lg:bg-contain lg:bg-center lg:h-hero-lg',
        md: 'md:bg-vector-pattern md:bg-no-repeat md:w-full md:text-center md:bg-contain md:bg-center md:h-hero-md',
        sm: 'sm:bg-vector-pattern sm:bg-no-repeat sm:w-full sm:text-center sm:bg-contain sm:bg-center sm:h-hero-sm',
        mobile: 'bg-vector-pattern bg-no-repeat w-full text-center bg-cover bg-center h-96'
    },
    heroBody: {
        xxl: '2xl:h-auto 2xl:w-full 2xl:px-24 2xl:py-8',
        xl: 'xl:h-auto xl:w-full xl:px-20 xl:py-6',
        lg: 'lg:h-auto lg:w-full lg:px-16 lg:py-4',
        md: 'md:h-auto md:w-full md:px-10 md:py-4',
        sm: 'sm:h-auto sm:w-full sm:px-10 sm:py-4',
        mobile: 'h-auto w-full px-4 py-4'
    },
    logoBody: {
        xxl: '2xl:grid 2xl:grid-cols-12 2xl:w-full 2xl:text-center 2xl:mb-2',
        xl: 'xl:grid xl:grid-cols-12 xl:w-full xl:text-center xl:mb-2',
        lg: 'lg:grid lg:grid-cols-12 lg:w-full lg:text-center lg:mb-2',
        md: 'md:grid md:grid-cols-12 md:w-full md:text-center md:mb-2',
        sm: 'sm:grid sm:grid-cols-12 sm:w-full sm:text-center sm:mb-2',
        mobile: 'grid grid-cols-2 w-full text-center mb-2 gap-2'
    },
    logoBisnisTop: {
        xxl: '2xl:col-start-1 2xl:h-14 2xl:px-2 2xl:bg-logo-bisnis-top 2xl:bg-contain 2xl:bg-no-repeat',
        xl: 'xl:col-start-1 xl:h-14 xl:px-2 xl:bg-logo-bisnis-top xl:bg-contain xl:bg-no-repeat',
        lg: 'lg:col-start-1 lg:h-14 lg:px-2 lg:bg-logo-bisnis-top lg:bg-contain lg:bg-no-repeat',
        md: 'md:col-start-1 md:h-14 md:px-2 md:bg-logo-bisnis-top md:bg-contain md:bg-no-repeat',
        sm: 'sm:col-start-1 sm:h-14 sm:px-2 sm:bg-logo-bisnis-top sm:bg-contain sm:bg-no-repeat',
        mobile: 'h-6 px-2 bg-logo-bisnis-top bg-contain bg-no-repeat ',
    },
    logoIndonesiaMajuTop: {
        xxl: '2xl:h-20 2xl:px-2 2xl:bg-logo-indonesia-maju-top 2xl:bg-contain 2xl:bg-right 2xl:bg-no-repeat 2xl:col-end-13 2xl:col-span-2',
        xl: 'xl:h-16 xl:px-2 xl:bg-logo-indonesia-maju-top xl:bg-contain xl:bg-right xl:bg-no-repeat xl:col-end-13 xl:col-span-2',
        lg: 'lg:h-14 lg:px-2 lg:bg-logo-indonesia-maju-top lg:bg-contain lg:bg-right lg:bg-no-repeat lg:col-end-13 lg:col-span-2',
        md: 'md:h-10 md:px-2 md:bg-logo-indonesia-maju-top md:bg-contain md:bg-right md:bg-no-repeat md:col-end-13 md:col-span-2',
        sm: 'sm:h-10 sm:px-2 sm:bg-logo-indonesia-maju-top sm:bg-contain sm:bg-right sm:bg-no-repeat sm:col-end-13 sm:col-span-2',
        mobile: 'h-14 px-2 bg-logo-indonesia-maju-top bg-contain bg-right bg-no-repeat ',
    },
    heroText: {
        xxl: '2xl:grid 2xl:grid-rows-2 2xl:text-center 2xl:text-white 2xl:w-full 2xl:h-full 2xl:mt-24 2xl:gap-10',
        xl: 'xl:grid xl:grid-rows-2 xl:text-center xl:text-white xl:w-full xl:h-full xl:mt-20 xl:gap-4',
        lg: 'lg:grid lg:grid-rows-2 lg:text-center lg:text-white lg:w-full lg:h-full lg:mt-20 lg:gap-2',
        md: 'md:grid md:grid-cols-1 md:text-center md:text-white md:w-full md:h-full md:mt-8 md:gap-4',
        sm: 'sm:grid sm:grid-cols-1 sm:text-center sm:text-white sm:w-full sm:h-full sm:mt-2 sm:gap-2',
        mobile: 'grid grid-cols-auto text-center text-white w-full h-full mt-14 gap-6'
    },
    headline: {
        xxl: '2xl:font-tahu 2xl:text-8xl 2xl:h-full',
        xl: 'xl:font-tahu xl:text-7xl xl:h-full',
        lg: 'lg:font-tahu lg:text-6xl lg:h-full',
        md: 'md:font-tahu md:text-5xl md:h-18',
        sm: 'sm:font-tahu sm:text-4xl sm:h-12',
        mobile: 'font-tahu text-5xl h-full'
    },
    subHeadline: {
        xxl: '2xl:h-full 2xl:px-4 2xl:py-2 2xl:text-white 2xl:font-gotham 2xl:text-base',
        xl: 'xl:h-full xl:px-4 xl:py-2 xl:text-white xl:font-gotham xl:text-sm',
        lg: 'lg:h-full lg:px-4 lg:py-2 lg:text-white lg:font-gotham lg:text-xs',
        md: 'md:h-full md:px-4 md:py-2 md:text-white md:font-gotham md:text-2xs',
        sm: 'sm:h-full sm:px-4 sm:py-2 sm:text-white sm:font-gotham sm:text-2xs',
        mobile: 'h-full px-4 py-2 text-white font-gotham text-xs'
    },
    content: {
        xxl: '2xl:container 2xl:mx-auto 2xl:px-8 2xl:transform 2xl:-translate-y-72 ',
        xl: 'xl:container xl:mx-auto xl:px-8 xl:transform xl:-translate-y-60',
        lg: 'lg:container lg:mx-auto lg:px-8 xl:transform lg:-translate-y-48',
        md: 'md:container md:mx-auto md:px-8 md:transform md:-translate-y-36',
        sm: 'sm:container sm:mx-auto sm:px-8 sm:transform sm:-translate-y-32 ',
        mobile: 'container mx-auto px-8 transform -translate-y-24 '
    },
    videoBody: {
        xxl: '2xl:grid 2xl:grid-cols-12 2xl:h-auto 2xl:w-full ',
        xl: 'xl:grid xl:grid-cols-12 2xl:h-auto 2xl:w-full',
        lg: 'lg:grid lg:grid-cols-12 lg:h-auto lg:w-full',
        md: 'md:grid md:grid-cols-12 md:h-auto md:w-full',
        sm: 'sm:grid sm:grid-cols-12 sm:h-auto sm:w-full',
        mobile: 'grid grid-cols-12 h-auto w-full'
    },
    video: {
        xxl: '2xl:grid 2xl:grid-rows-6 2xl:bg-video-thumb 2xl:bg-contain 2xl:bg-center 2xl:bg-no-repeat 2xl:col-start-3 2xl:col-end-11 2xl:text-white 2xl:py-4 2xl:px-12 2xl:h-video-thumb-2xl',
        xl: 'xl:grid xl:grid-rows-6 xl:bg-video-thumb xl:bg-contain xl:bg-center xl:bg-no-repeat xl:col-start-3 xl:col-end-11 xl:text-white xl:py-4 xl:px-10 xl:h-video-thumb-xl',
        lg: 'lg:grid lg:grid-rows-6 lg:bg-video-thumb lg:bg-contain lg:bg-center lg:bg-no-repeat lg:col-start-3 lg:col-end-11 lg:text-white lg:py-4 lg:px-12 lg:h-video-thumb-lg',
        md: 'md:grid md:grid-rows-6 md:bg-video-thumb md:bg-contain md:bg-center md:bg-no-repeat md:col-start-3 md:col-end-11 md:text-white md:py-2 md:px-8 md:h-video-thumb-lg',
        sm: 'sm:grid sm:grid-rows-6 sm:bg-video-thumb sm:bg-contain sm:bg-center sm:bg-no-repeat sm:col-start-3 sm:col-end-11 sm:text-white sm:py-4 sm:px-2 sm:h-video-thumb-sm',
        mobile: 'grid grid-rows-6 bg-video-thumb bg-contain bg-no-repeat col-start-1 col-end-6 text-white p-2 h-video-thumb-sm text-white'
    },
    iconPlayer: {
        xxl: '2xl:row-start-7 2xl:bg-icon-player 2xl:bg-no-repeat 2xl:bg-contain 2xl:h-14 2xl:w-14 ',
        xl: 'xl:row-start-7 xl:bg-icon-player xl:bg-no-repeat xl:bg-contain xl:h-12 xl:w-12',
        lg: 'lg:row-start-7 lg:bg-icon-player lg:bg-no-repeat lg:bg-contain lg:h-10 lg:w-10',
        md: 'md:row-start-7 md:bg-icon-player md:bg-no-repeat md:bg-contain md:h-8 md:w-8',
        sm: 'sm:row-start-7 sm:bg-icon-player sm:bg-no-repeat sm:bg-contain sm:h-4 sm:w-4',
        mobile: 'row-start-7 bg-icon-player bg-no-repeat bg-contain h-4 w-4'
    },
    instagram: {
        xxl: '2xl:grid 2xl:grid-cols-12 2xl:gap-8 2xl:my-8',
        xl: 'xl:grid xl:grid-cols-12 xl:gap-8 xl:my-8',
        lg: 'lg:grid lg:grid-rows-auto lg:gap-8 ',
        md: 'md:grid md:grid-cols-12 md:gap-8 md:my-8',
        sm: 'sm:grid sm:grid-cols-12 sm:gap-8 sm:my-8',
        mobile: 'grid grid-cols-12 gap-8 my-8'
    },
    event1: {
        xxl: '2xl:bg-event-1-ig 2xl:bg-no-repeat 2xl:bg-center 2xl:bg-contain 2xl:h-event-2xl 2xl:col-start-3 2xl:col-span-4',
        xl: 'xl:bg-event-1-ig xl:bg-no-repeat xl:bg-center xl:bg-contain xl:h-event-xl xl:col-start-3 xl:col-span-4',
        lg: 'lg:bg-event-1-ig lg:bg-no-repeat lg:bg-center lg:bg-contain lg:h-event-lg',
        md: 'md:bg-event-1-ig md:bg-no-repeat md:bg-center md:bg-contain md:h-event-md md:col-start-3 md:col-span-4',
        sm: 'sm:bg-event-1-ig sm:bg-no-repeat sm:bg-center sm:bg-contain sm:h-event-sm sm:col-start-3 sm:col-span-4',
        mobile: 'bg-event-1-ig bg-no-repeat bg-center bg-contain h-event-2xl col-start-3 col-span-4'
    },
    logoIg: {
        xxl: '2xl:bg-logo-ig-1 2xl:bg-no-repeat 2xl:bg-contain 2xl:mt-10 2xl:h-logo-ig-2xl 2xl:bg-bottom 2xl:row-span-3',
        xl: 'xl:bg-logo-ig-1 xl:bg-no-repeat xl:bg-contain xl:mt-10 xl:h-logo-ig-xl xl:bg-bottom xl:row-span-3',
        lg: 'lg:bg-logo-ig-1 lg:bg-no-repeat lg:h-logo-ig-lg lg:bg-bottom lg:row-span-3',
        md: 'md:bg-logo-ig-1 md:bg-no-repeat md:h-logo-ig-md md:bg-bottom md:row-span-3',
        sm: 'sm:bg-logo-ig-1 sm:bg-no-repeat sm:h-logo-ig-sm sm:bg-bottom sm:row-span-3',
        mobile: 'bg-logo-ig-1 bg-no-repeat h-logo-ig-2xl bg-bottom row-span-3',
    },
    bgSpeaker1: {
        xxl: '2xl:bg-speaker-1-1 2xl:bg-no-repeat 2xl:bg-contain 2xl:bg-center 2xl:h-speaker-2xl',
        xl: 'xl:bg-speaker-1-1 xl:bg-no-repeat xl:bg-contain xl:bg-center xl:h-speaker-xl',
        lg: 'lg:bg-speaker-1-1 lg:bg-no-repeat lg:bg-contain lg:bg-center lg:h-speaker-lg',
        md: 'md:bg-speaker-1-1 md:bg-no-repeat md:bg-contain md:bg-center md:h-speaker-md',
        sm: 'sm:bg-speaker-1-1 sm:bg-no-repeat sm:bg-contain sm:bg-center sm:h-speaker-sm',
        mobile: 'bg-speaker-1-1 bg-no-repeat bg-contain bg-center h-speaker-2xl',
    },
    bgSpeaker2: {
        xxl: '2xl:bg-speaker-1-2 2xl:bg-no-repeat 2xl:bg-contain 2xl:bg-center 2xl:h-speaker-2xl',
        xl: 'xl:bg-speaker-1-2 xl:bg-no-repeat xl:bg-contain xl:bg-center xl:h-speaker-xl',
        lg: 'lg:bg-speaker-1-2 lg:bg-no-repeat lg:bg-contain lg:bg-center lg:h-speaker-lg',
        md: 'md:bg-speaker-1-2 md:bg-no-repeat md:bg-contain md:bg-center md:h-speaker-md',
        sm: 'sm:bg-speaker-1-2 sm:bg-no-repeat sm:bg-contain sm:bg-center sm:h-speaker-sm',
        mobile: 'bg-speaker-1-2 bg-no-repeat bg-contain bg-center h-speaker-2xl',
    },
    nameSpeaker: {
        xxl: '2xl:bg-bg-name-speaker1 2xl:bg-no-repeat 2xl:bg-auto 2xl:bg-center 2xl:text-center 2xl:text-white',
        xl: 'xl:bg-bg-name-speaker1 xl:bg-no-repeat xl:bg-auto xl:bg-center xl:text-center xl:text-white',
        lg: 'lg:bg-bg-name-speaker1 lg:bg-no-repeat lg:bg-auto lg:bg-center lg:text-center lg:text-white',
        md: 'md:bg-bg-name-speaker1 md:bg-no-repeat md:bg-auto md:bg-center md:text-center md:text-white',
        sm: 'sm:bg-bg-name-speaker1 sm:bg-no-repeat sm:bg-auto sm:bg-center sm:text-center sm:text-white',
        mobile: 'bg-bg-name-speaker1 bg-no-repeat bg-auto bg-center text-center text-white',
    },
    event2: {
        xxl: '2xl:bg-event-2-ig 2xl:bg-no-repeat 2xl:bg-center 2xl:bg-contain 2xl:h-event-2xl 2xl:col-start-7 2xl:col-span-4',
        xl: 'xl:bg-event-2-ig xl:bg-no-repeat xl:bg-center xl:bg-contain xl:h-event-xl xl:col-start-7 xl:col-span-4',
        lg: 'lg:bg-event-2-ig lg:bg-no-repeat lg:bg-center lg:bg-contain lg:h-event-lg',
        md: 'md:bg-event-2-ig md:bg-no-repeat md:bg-center md:bg-contain md:h-event-md md:col-start-7 md:col-span-4',
        sm: 'sm:bg-event-2-ig sm:bg-no-repeat sm:bg-center sm:bg-contain sm:h-event-sm sm:col-start-7 sm:col-span-4',
        mobile: 'bg-event-2-ig bg-no-repeat bg-center bg-contain h-event-2xl col-start-7 col-span-4'
    },
    presentedBy: {
        xxl: '2xl:grid 2xl:grid-cols-12 2xl:mb-32',
        xl: 'xl:grid xl:grid-cols-12 xl:mb-32',
        lg: 'lg:grid lg:grid-cols-12 lg:mb-32',
        md: 'md:grid md:grid-cols-12 md:mb-32',
        sm: 'sm:grid sm:grid-cols-12 sm:mb-32',
        mobile: 'grid grid-cols-12 mb-32',
    },
    presentedByBody: {
        xxl: '2xl:col-start-3 2xl:col-end-11',
        xl: 'xl:col-start-3 xl:col-end-11',
        lg: 'lg:col-start-3 lg:col-end-11',
        md: 'md:col-start-3 md:col-end-11',
        mobile: 'col-start-3 col-end-11',
    },
    presentedByText: {
        xxl: '2xl:text-center',
        xl: 'xl:text-center',
        lg: 'lg:text-center',
        md: 'md:text-center',
        mobile: 'text-center',
    },
    presentedByLogo: {
        xxl: '2xl:grid 2xl:grid-cols-12',
        xl: 'xl:grid xl:grid-cols-12',
        lg: 'lg:grid lg:grid-cols-12',
        md: 'md:grid md:grid-cols-12',
        sm: 'sm:grid sm:grid-cols-12',
        mobile: 'grid grid-cols-12',
    },
    presentedByLogoBody: {
        xxl: '2xl:col-start-5 2xl:col-end-9 2xl:grid 2xl:grid-cols-2',
        xl: 'xl:col-start-5 xl:col-end-9 xl:grid xl:grid-cols-2',
        lg: 'lg:col-start-5 lg:col-end-9 lg:grid lg:grid-cols-2',
        md: 'md:col-start-5 md:col-end-9 md:grid md:grid-cols-2',
        sm: 'sm:col-start-5 sm:col-end-9 sm:grid sm:grid-cols-2',
        mobile: 'col-start-5 col-end-9 grid grid-cols-2',
    },
    logoBankBtn: {
        xxl: '2xl:bg-logo-bank-btn 2xl:bg-contain 2xl:bg-no-repeat 2xl:bg-left 2xl:h-logo-bank-btn',
        xl: 'xl:bg-logo-bank-btn xl:bg-contain xl:bg-no-repeat xl:bg-left xl:h-logo-bank-btn',
        lg: 'lg:bg-logo-bank-btn lg:bg-contain lg:bg-no-repeat lg:bg-left lg:h-logo-bank-btn',
        md: 'md:bg-logo-bank-btn md:bg-contain md:bg-no-repeat md:bg-left md:h-logo-bank-btn',
        sm: 'sm:bg-logo-bank-btn sm:bg-contain sm:bg-no-repeat sm:bg-left sm:h-logo-bank-btn',
        mobile: 'bg-logo-bank-btn bg-contain bg-no-repeat bg-left h-logo-bank-btn',
    },
    logoWaskita: {
        xxl: '2xl:bg-logo-waskita 2xl:bg-contain 2xl:bg-no-repeat 2xl:bg-right 2xl:h-logo-waskita',
        xl: 'xl:bg-logo-waskita xl:bg-contain xl:bg-no-repeat xl:bg-right xl:h-logo-waskita',
        lg: 'lg:bg-logo-waskita lg:bg-contain lg:bg-no-repeat lg:bg-right lg:h-logo-waskita',
        md: 'md:bg-logo-waskita md:bg-contain md:bg-no-repeat md:bg-right md:h-logo-waskita',
        mobile: 'mobile:bg-logo-waskita mobile:bg-contain mobile:bg-no-repeat mobile:bg-right mobile:h-logo-waskita',
    },
    banner: {
        xxl: '2xl:grid 2xl:grid-cols-12 2xl:mb-8',
        xl: 'xl:grid xl:grid-cols-12 xl:mb-1',
        lg: 'lg:grid lg:grid-cols-12 lg:mb-8',
        md: 'md:grid md:grid-cols-12 md:mb-8',
        mobile: 'grid grid-cols-12 mb-8',
    },
    bannerText: {
        xxl: '2xl:bg-shape b2xl:g-no-repeat 2xl:bg-contain 2xl:h-presiden-banner 2xl:col-start-3 2xl:col-end-11',
        xl: 'xl:bg-shape bxl:g-no-repeat xl:bg-contain xl:h-presiden-banner xl:col-start-3 xl:col-end-11',
        lg: 'lg:bg-shape blg:g-no-repeat lg:bg-contain lg:h-presiden-banner lg:col-start-3 lg:col-end-11',
        md: 'md:bg-shape bmd:g-no-repeat md:bg-contain md:h-presiden-banner md:col-start-3 md:col-end-11',
        sm: 'sm:bg-shape bsm:g-no-repeat sm:bg-contain sm:h-presiden-banner sm:col-start-3 sm:col-end-11',
        mobile: 'bg-shape bg-no-repeat bg-contain h-presiden-banner col-start-3 col-end-11',
    },
    bannerBg: {
        xxl: '2xl:bg-presiden-banner 2xl:bg-no-repeat 2xl:bg-contain 2xl:h-presiden-banner 2xl:grid 2xl:grid-rows-auto 2xl:col-start-3 2xl:col-end-11 2xl:text-white 2xl:text-center',
        xl: 'xl:bg-presiden-banner xl:bg-no-repeat xl:bg-contain xl:h-presiden-banner xl:grid xl:grid-rows-auto xl:col-start-3 xl:col-end-11 xl:text-white xl:text-center',
        lg: 'lg:bg-presiden-banner lg:bg-no-repeat lg:bg-contain lg:h-presiden-banner lg:grid lg:grid-rows-auto lg:col-start-3 lg:col-end-11 lg:text-white lg:text-center',
        md: 'md:bg-presiden-banner md:bg-no-repeat md:bg-contain md:h-presiden-banner md:grid md:grid-rows-auto md:col-start-3 md:col-end-11 md:text-white md:text-center',
        sm: 'sm:bg-presiden-banner sm:bg-no-repeat sm:bg-contain sm:h-presiden-banner sm:grid sm:grid-rows-auto sm:col-start-3 sm:col-end-11 sm:text-white sm:text-center',
        mobile: 'bg-presiden-banner bg-no-repeat bg-contain h-presiden-banner grid grid-rows-auto col-start-3 col-end-11 text-white text-center',
    }
}